version: "2.32.4"
services:
  database:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres