DROP TABLE IF EXISTS account CASCADE;

CREATE TABLE IF NOT EXISTS account (
    id SERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

DROP TABLE IF EXISTS wallet CASCADE;

CREATE TABLE IF NOT EXISTS wallet (
    id SERIAL PRIMARY KEY,
    account_id BIGINT UNIQUE NOT NULL REFERENCES account,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

DROP TABLE IF EXISTS transaction CASCADE;

CREATE TABLE IF NOT EXISTS transaction(
    id SERIAL PRIMARY KEY,
    wallet_id BIGINT NOT NULL REFERENCES wallet,
    amount DECIMAL(10, 2) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
